# -*- coding: utf-8 -*-
"""Golden seccion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wke_WCn7AswavkCPympPSmb2ndXeJMDB
"""



"""$$x_1 = /tha $$
##importamos paquetes##
  import numpy as np
"""

import numpy as np
import matplotlib.pyplot as plt
import

x= np.linspace(-1,3,100)
x0= np.exp(-1)

def f(x):
  return (x-x0)**2 + np.exp(-5*(x -  0.5 - x0)**2)

plt.plot(x,f(x))

def g(x):
  return diff.np(f(x))

print()